#!/bin/sh -f

bush_home=`pwd`/../../bush

${bush_home}/find_rm ../comres '*.*'

#/////////////////////////////////////////////////////////////
#/// from ioda: //////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

. ../../ioda/mgr/cp_std

for file in ${files} ; do
  /bin/cp ../../ioda/res/${file} ../comres/.
done


/bin/cp ../../ioda/res/ioda.style ../comres/pmx.style

#/////////////////////////////////////////////////////////////
#/// from inlib: /////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

. ../../inexlib/inlib/mgr/cp_insh

for file in ${files} ; do
  /bin/cp ../../inexlib/inlib/inlib/insh/scripts/${file} ../comres/.
done

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////
files="pmx.ftp"
files="${files} lhcb_side_256_128.jpg cam_lhcb_front.jpg cam_lhcb_side.jpg"
files="${files} lhcbfull.root lhcb.vds"
files="${files} bdpi_ghost.dst"
files="${files} icon.jpg favicon.ico startup.insh"
files="${files} about.insh"
files="${files} event.insh"
files="${files} camera_front.insh"
files="${files} camera_side.insh"
files="${files} camera_top.insh"
files="${files} camera_3d.insh"
files="${files} camera_default.insh"
files="${files} camera_setup_3d.insh"
files="${files} default_geometry.insh"

files="${files} gui_main.insh"
files="${files} gui_detector.insh"

find ../res -name '*.bsg' -exec /bin/cp {} ../comres/. \;
find ../res -name '*.cdf' -exec /bin/cp {} ../comres/. \;

${bush_home}/find_rm ../comres 'evt_*.bsg'
/bin/cp ../res/evt_0.bsg ../comres/.
/bin/cp ../res/evt_3.bsg ../comres/.
/bin/cp ../res/evt_bs_mu_mu_2012_0.bsg ../comres/.
/bin/cp ../res/evt_bs_mu_mu_2012_3.bsg ../comres/.
/bin/cp ../res/evt_bu_2_jpsi_k_00011917_00000048_1_2.bsg ../comres/.
/bin/cp ../res/evt_bu_2_jpsi_k_00011917_00000048_1_3.bsg ../comres/.

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res
