#include <inlib/fog/scene>
#include <inlib/sg/_switch>
#include <inlib/sg/arrow_button>
#include <inlib/sg/atb_vertices>
#include <inlib/sg/axes>
#include <inlib/sg/axis>
#include <inlib/sg/back_area>
#include <inlib/sg/base_camera>
#include <inlib/sg/base_fch>
#include <inlib/sg/base_freetype>
#include <inlib/sg/base_list>
#include <inlib/sg/base_text>
#include <inlib/sg/bcub>
#include <inlib/sg/bifacet>
#include <inlib/sg/button_grid>
#include <inlib/sg/cfitsio>
#include <inlib/sg/cfitsio_stars>
#include <inlib/sg/circle>
#include <inlib/sg/circle_arc>
#include <inlib/sg/colback>
#include <inlib/sg/color>
#include <inlib/sg/colors>
#include <inlib/sg/cone_hat>
#include <inlib/sg/cube>
#include <inlib/sg/cube_manip>
#include <inlib/sg/depth_test>
#include <inlib/sg/doc_anim>
#include <inlib/sg/draw_style>
#include <inlib/sg/edvalop>
#include <inlib/sg/entries>
#include <inlib/sg/entry>
#include <inlib/sg/facet>
#include <inlib/sg/field3d>
#include <inlib/sg/field_cut>
#include <inlib/sg/frustum>
#include <inlib/sg/geo>
#include <inlib/sg/ghost>
#include <inlib/sg/h1d>
#include <inlib/sg/healpix>
#include <inlib/sg/hips>
#include <inlib/sg/holder>
#include <inlib/sg/icosahedron_sphere>
#include <inlib/sg/image_button>
#include <inlib/sg/image_grid>
#include <inlib/sg/image_text_button>
#include <inlib/sg/infos>
#include <inlib/sg/infos_box>
#include <inlib/sg/keyboard>
#include <inlib/sg/legend>
#include <inlib/sg/line_set>
#include <inlib/sg/line_style>
#include <inlib/sg/list>
#include <inlib/sg/lrbt>
#include <inlib/sg/markers>
#include <inlib/sg/matrix>
#include <inlib/sg/matrix4manip>
#include <inlib/sg/normal>
#include <inlib/sg/numeric>
#include <inlib/sg/ortho>
#include <inlib/sg/parabolic_anim>
#include <inlib/sg/perspective>
#include <inlib/sg/plots>
#include <inlib/sg/plotter>
#include <inlib/sg/polyhedron>
#include <inlib/sg/progress>
#include <inlib/sg/quadrilateral>
#include <inlib/sg/rgba>
#include <inlib/sg/ring>
#include <inlib/sg/rotate_anim>
#include <inlib/sg/screens>
#include <inlib/sg/scroll_infos>
#include <inlib/sg/scroll_text>
#include <inlib/sg/selectable>
#include <inlib/sg/selection>
#include <inlib/sg/simple_button>
#include <inlib/sg/slider>
#include <inlib/sg/snow_anim>
#include <inlib/sg/sphere>
#include <inlib/sg/style>
#include <inlib/sg/switch_anim>
#include <inlib/sg/tex_quadrilateral>
#include <inlib/sg/tex_rect>
#include <inlib/sg/tex_rect_anim>
#include <inlib/sg/tex_sphere>
#include <inlib/sg/tex_sphere_anim>
#include <inlib/sg/text>
#include <inlib/sg/text_button>
#include <inlib/sg/text_hershey>
#include <inlib/sg/text_style>
#include <inlib/sg/text_valop>
#include <inlib/sg/torche>
#include <inlib/sg/transporter_anim>
#include <inlib/sg/tube>
#include <inlib/sg/vertices>
#include <inlib/sg/xmas_tree>

inline void add_all(inlib::sg::group& a_grp,inlib::sg::base_freetype& a_ttf) {

  a_grp.add(new inlib::fog::scene);
  a_grp.add(new inlib::sg::_switch);
  a_grp.add(new inlib::sg::arrow_button);
  a_grp.add(new inlib::sg::atb_vertices);
  a_grp.add(new inlib::sg::axes(a_ttf));
  a_grp.add(new inlib::sg::axis(a_ttf));
  a_grp.add(new inlib::sg::back_area);
  a_grp.add(new inlib::sg::bcub);
  a_grp.add(new inlib::sg::bifacet);
  a_grp.add(new inlib::sg::cfitsio);
  a_grp.add(new inlib::sg::circle);
  a_grp.add(new inlib::sg::circle_arc);
  a_grp.add(new inlib::sg::colback);
  a_grp.add(new inlib::sg::color);
  a_grp.add(new inlib::sg::colors(a_ttf));
  a_grp.add(new inlib::sg::cone_hat);
  a_grp.add(new inlib::sg::cube);
  a_grp.add(new inlib::sg::cube_manip);
  a_grp.add(new inlib::sg::depth_test);
  a_grp.add(new inlib::sg::draw_style);
  a_grp.add(new inlib::sg::edvalop(a_ttf));
  a_grp.add(new inlib::sg::entries(a_ttf));
  a_grp.add(new inlib::sg::entry(a_ttf));
  a_grp.add(new inlib::sg::facet);
  a_grp.add(new inlib::sg::field3d);
  a_grp.add(new inlib::sg::field_cut);
  a_grp.add(new inlib::sg::frustum);
  a_grp.add(new inlib::sg::ghost);
  a_grp.add(new inlib::sg::h1d(a_ttf));
  a_grp.add(new inlib::sg::healpix);
  a_grp.add(new inlib::sg::icosahedron_sphere);
  a_grp.add(new inlib::sg::image_button);
  a_grp.add(new inlib::sg::image_text_button(a_ttf));
  a_grp.add(new inlib::sg::infos);
  a_grp.add(new inlib::sg::infos_box(a_ttf));
  a_grp.add(new inlib::sg::keyboard(a_ttf));
  a_grp.add(new inlib::sg::legend(a_ttf));
  a_grp.add(new inlib::sg::line_set);
  a_grp.add(new inlib::sg::line_style);
  a_grp.add(new inlib::sg::list(a_ttf));
  a_grp.add(new inlib::sg::lrbt);
  a_grp.add(new inlib::sg::markers);
  a_grp.add(new inlib::sg::matrix);
  a_grp.add(new inlib::sg::matrix4manip);
  a_grp.add(new inlib::sg::normal);
  a_grp.add(new inlib::sg::numeric(a_ttf));
  a_grp.add(new inlib::sg::ortho);
  a_grp.add(new inlib::sg::perspective);
  a_grp.add(new inlib::sg::plots(a_ttf));
  a_grp.add(new inlib::sg::plotter(a_ttf));
  a_grp.add(new inlib::sg::polyhedron);
  a_grp.add(new inlib::sg::progress);
  a_grp.add(new inlib::sg::quadrilateral);
  a_grp.add(new inlib::sg::rgba);
  a_grp.add(new inlib::sg::ring);
  a_grp.add(new inlib::sg::screens);
  a_grp.add(new inlib::sg::scroll_infos(a_ttf));
  a_grp.add(new inlib::sg::scroll_text(a_ttf));
  a_grp.add(new inlib::sg::selection);
  a_grp.add(new inlib::sg::simple_button);
  a_grp.add(new inlib::sg::slider);
  a_grp.add(new inlib::sg::sphere);
  a_grp.add(new inlib::sg::style);
  a_grp.add(new inlib::sg::tex_quadrilateral);
  a_grp.add(new inlib::sg::tex_rect);
  a_grp.add(new inlib::sg::tex_sphere);
  a_grp.add(new inlib::sg::text(a_ttf));
  a_grp.add(new inlib::sg::text_button(a_ttf));
  a_grp.add(new inlib::sg::text_hershey);
  a_grp.add(new inlib::sg::text_style);
  a_grp.add(new inlib::sg::text_valop(a_ttf));
  a_grp.add(new inlib::sg::torche);
  a_grp.add(new inlib::sg::tube);
  a_grp.add(new inlib::sg::vertices);
  a_grp.add(new inlib::sg::xmas_tree);
}
