#!/bin/sh -f

#set -x

ndk_home=/usr/local/Android/android-ndk-r17

${ndk_home}/prebuilt/darwin-x86_64/bin/python ${ndk_home}/simpleperf/report.py

# to see call graph :
#${ndk_home}/prebuilt/darwin-x86_64/bin/python ${ndk_home}/simpleperf/report.py -g --symfs .

#${ndk_home}/simpleperf/bin/darwin/x86_64/simpleperf report --dsos /data/app/fr.in2p3.lal.pmx-o2k0OkOcl9oDtPhj7nKCYA==/lib/arm64/libpmx.so  --symbols "inlib::sg::polyhedron::render(inlib::sg::render_action&)"

