#!/bin/sh -f

# WARNING : in ${ndk_home}/simpleperf/binary_cache_builder.py --ndk-path must be changed to --ndk_path.
# WARNING : if mot using the below -r option, in ${ndk_home}/simpleperf/app_profiler.py, the line :
#                              default='-e task-clock:u -f 1000 -g --duration 10',
#           must be changed to :
#                              default='"-e task-clock:u -f 1000 -g --duration 10"',

# app must be build with an AndroidManifest.xml having the android:debuggable="true" in <application>, for example :
#    <application android:label="@string/app_name" android:icon="@drawable/icon" android:debuggable="true">


#set -x

ndk_home=/usr/local/Android/android-ndk-r17

#record_opts='"-e task-clock:u -f 1000 -g --duration 21"'
record_opts='-e task-clock:u -f 1000 -g --duration 21'

${ndk_home}/prebuilt/darwin-x86_64/bin/python ${ndk_home}/simpleperf/app_profiler.py --ndk_path ${ndk_home} -p fr.in2p3.lal.pmx -lib /Users/barrand/private/dev/softinex/pmx/Android/libs/arm64-v8a -r "${record_opts}"
